modLoader="javafml"
loaderVersion="[64,)"
license="${license}"
issueTrackerURL="https://github.com/vakiliner/ChatComponentAPI/issues"

[[mods]]
modId="chatcomponentapi"
version="${version}"
displayName="ChatComponentAPI"
authors="VAKiliner"
description='''
ChatComponentAPI для ChatModerator
'''
displayURL="https://github.com/vakiliner/ChatComponentAPI"
updateJSONURL="https://raw.githubusercontent.com/vakiliner/ChatComponentAPI/refs/heads/main/update.json"

[[dependencies.chatcomponentapi]]
	modId="forge"
	mandatory=true
	versionRange="[64,)"
[[dependencies.chatcomponentapi]]
	modId="minecraft"
	mandatory=true
	versionRange="[26.1.2,26.2)"
