plugins {
	id 'dev.architectury.loom'
}

dependencies {
	implementation project(':base')
	testImplementation project(path: ':base', configuration: 'test')
	minecraft "net.minecraft:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

loom {
	mixin {
		defaultRefmapName = "${project.archives_base_name}-fabric-refmap.json"

		useLegacyMixinAp = true
	}
}

processResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

java.withSourcesJar()

task remapDevJar(type: net.fabricmc.loom.task.RemapJarTask) {
	var task = project.tasks.getByName('devJar')
	archiveBaseName = "Dev${project.base.archivesName.get()}"
	input.set(task.archiveFile)
}

devJar.finalizedBy remapDevJar
