plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

dependencies {
	implementation project(':base')
	testImplementation project(path: ':base', configuration: 'testOutputElements')
	minecraft group: 'com.mojang', name: 'minecraft', version: project.minecraft_version
	implementation group: 'net.fabricmc', name: 'fabric-loader', version: project.loader_version

	implementation group: 'net.fabricmc.fabric-api', name: 'fabric-api', version: project.fabric_api
}

loom {
	mixin {
		defaultRefmapName = 'ChatComponentAPI-fabric-refmap.json'
	}
}

processResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}
