plugins {
	id 'dev.architectury.loom' version "${loom_version}" apply false
}

var base = findProject(':base')
var craftbukkit = findProject(':craftbukkit')
var spigot = findProject(':spigot')
var paper = findProject(':paper')
var fabric = findProject(':fabric')
var forge = findProject(':forge')

allprojects {
	apply plugin: 'java'

	java.toolchain.languageVersion = JavaLanguageVersion.of(8)

	var replaceProperties = [
		version: project.version,
		license: project.license,
	]

	processResources {
		inputs.properties replaceProperties
	}

	processTestResources {
		inputs.properties replaceProperties
	}

	tasks.named('test') {
		failOnNoDiscoveredTests = false
	}

	tasks.withType(JavaCompile).configureEach {
		options.encoding = 'UTF-8'
	}
}

subprojects {
	apply plugin: 'java'

	it.base {
		archivesName = "${project.archives_base_name}-${project.display_name}"
	}

	task devJar(type: Jar) {
		var task = tasks.getByName('jar')
		archiveFileName = "Dev${task.archiveFileName.get()}"
		destinationDirectory = task.destinationDirectory
		duplicatesStrategy = DuplicatesStrategy.EXCLUDE
		from project.sourceSets.test.output
		from zipTree(task.archiveFile)
		manifest {
			from task.manifest
		}
	}
}

def generateManifestAttributes() {
	var attributes = [
		'Built-Timestamp': new Date(),
		'Built-OS': System.getProperty('os.name'),
	]
	var githubActions = System.getenv('GITHUB_ACTIONS')
	var githubSha = System.getenv('GITHUB_SHA')
	var termProgram = System.getenv('TERM_PROGRAM')
	if (githubActions != null) attributes['Built-GitHub-Actions'] = githubActions
	if (githubSha != null) attributes['Built-GitHub-Sha'] = githubSha
	if (termProgram != null) attributes['Built-Term-Program'] = termProgram
	return attributes
}

jar {
	if (base != null) evaluationDependsOn(base.getName())
	if (craftbukkit != null) evaluationDependsOn(craftbukkit.getName())
	if (spigot != null) evaluationDependsOn(spigot.getName())
	if (paper != null) evaluationDependsOn(paper.getName())
	if (fabric != null) evaluationDependsOn(fabric.getName())
	if (forge != null) evaluationDependsOn(forge.getName())

	var baseJar = base != null ? base.tasks.getByName('jar') : null
	var craftbukkitJar = craftbukkit != null ? craftbukkit.tasks.getByName('jar') : null
	var spigotJar = spigot != null ? spigot.tasks.getByName('jar') : null
	var paperJar = paper != null ? paper.tasks.getByName('jar') : null
	var fabricJar = fabric != null ? fabric.tasks.getByName('jar') : null
	var fabricRemapJar = fabric != null ? fabric.tasks.getByName('remapJar') : null
	var forgeJar = forge != null ? forge.tasks.getByName('jar') : null
	var forgeRemapJar = forge != null ? forge.tasks.getByName('remapJar') : null

	from 'LICENSE'
	if (baseJar != null) from(zipTree(baseJar.archiveFile))
	if (craftbukkitJar != null) from(zipTree(craftbukkitJar.archiveFile))
	if (spigotJar != null) from(zipTree(spigotJar.archiveFile))
	if (paperJar != null) from(zipTree(paperJar.archiveFile))
	if (fabricRemapJar != null) from(zipTree(fabricRemapJar.archiveFile))
	if (forgeRemapJar != null) from(zipTree(forgeRemapJar.archiveFile))

	manifest {
		if (baseJar != null) from baseJar.manifest
		if (craftbukkitJar != null) from craftbukkitJar.manifest
		if (spigotJar != null) from spigotJar.manifest
		if (paperJar != null) from paperJar.manifest
		if (fabricJar != null) from fabricJar.manifest
		if (forgeJar != null) from forgeJar.manifest
		attributes(generateManifestAttributes())
	}
}

task devJar(type: Jar) {
	if (base != null) evaluationDependsOn(base.getName())
	if (craftbukkit != null) evaluationDependsOn(craftbukkit.getName())
	if (spigot != null) evaluationDependsOn(spigot.getName())
	if (paper != null) evaluationDependsOn(paper.getName())
	if (fabric != null) evaluationDependsOn(fabric.getName())
	if (forge != null) evaluationDependsOn(forge.getName())

	archiveBaseName = "Dev${project.base.archivesName.get()}"

	var baseJar = base != null ? base.tasks.getByName('devJar') : null
	var craftbukkitJar = craftbukkit != null ? craftbukkit.tasks.getByName('devJar') : null
	var spigotJar = spigot != null ? spigot.tasks.getByName('devJar') : null
	var paperJar = paper != null ? paper.tasks.getByName('devJar') : null
	var fabricJar = fabric != null ? fabric.tasks.getByName('devJar') : null
	var fabricRemapJar = fabric != null ? fabric.tasks.getByName('remapDevJar') : null
	var forgeJar = forge != null ? forge.tasks.getByName('devJar') : null
	var forgeRemapJar = forge != null ? forge.tasks.getByName('remapDevJar') : null

	from 'LICENSE'
	if (baseJar != null) from(zipTree(baseJar.archiveFile))
	if (craftbukkitJar != null) from(zipTree(craftbukkitJar.archiveFile))
	if (spigotJar != null) from(zipTree(spigotJar.archiveFile))
	if (paperJar != null) from(zipTree(paperJar.archiveFile))
	if (fabricRemapJar != null) from(zipTree(fabricRemapJar.archiveFile))
	if (forgeRemapJar != null) from(zipTree(forgeRemapJar.archiveFile))

	manifest {
		if (baseJar != null) from baseJar.manifest
		if (craftbukkitJar != null) from craftbukkitJar.manifest
		if (spigotJar != null) from spigotJar.manifest
		if (paperJar != null) from paperJar.manifest
		if (fabricJar != null) from fabricJar.manifest
		if (forgeJar != null) from forgeJar.manifest
		attributes(generateManifestAttributes())
	}
}
