plugins {
	id 'java'
}

repositories {
	maven {
		name = 'Codemc'
		url = 'https://repo.codemc.io/repository/nms/'
	}

	maven {
		name = 'MinecraftLibs'
		url = 'https://libraries.minecraft.net'
	}

	mavenCentral()
}

dependencies {
	implementation project(':core')
	implementation "org.bukkit:bukkit:${project.minecraft_version}-${project.bukkit_version}"
	implementation "com.mojang:authlib:${project.authlib_version}"
}

processResources {
	filesMatching('plugin.yml') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('plugin.yml') {
		expand inputs.properties
	}
}

jar {
	exclude 'vakiliner/chatcomponentapi/spigot/**'
	exclude 'vakiliner/chatcomponentapi/paper/**'
}
