plugins {
	id 'dev.architectury.loom'
}

dependencies {
	implementation project(':base')
	testImplementation project(path: ':base', configuration: 'test')
	minecraft "net.minecraft:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

loom {
	mixin {
		defaultRefmapName = "${project.archives_base_name}-forge-refmap.json"

		useLegacyMixinAp = true
	}
}

processResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

java.withSourcesJar()

task remapDevJar(type: net.fabricmc.loom.task.RemapJarTask) {
	var task = project.tasks.getByName('devJar')
	archiveBaseName = "Dev${project.base.archivesName.get()}"
	input.set(task.archiveFile)
}

devJar.finalizedBy remapDevJar
