plugins {
	id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

minecraft {
	mappings channel: mapping_channel, version: minecraft_version

	runs {
		configureEach {
			workingDir = layout.projectDirectory.dir('run')

			systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
			systemProperty 'forge.enabledGameTestNamespaces', 'chatcomponentapi'
		}

		register('client')

		register('server') {
			args '--nogui'
		}

		register('gameTestServer')

		register('data') {
			workingDir = layout.projectDirectory.dir('run-data')

			args '--mod', 'chatcomponentapi', '--all', '--output', layout.projectDirectory.dir('src/generated/resources/'), '--existing', layout.projectDirectory.dir('src/main/resources/')
		}
	}
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
	minecraft.mavenizer(it) // In Kotlin, it = this
	maven fg.forgeMaven
	maven fg.minecraftLibsMaven
	mavenCentral()
}

dependencies {
	implementation project(':base')
	testImplementation project(path: ':base', configuration: 'testOutputElements')
	implementation minecraft.dependency("net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}")
}

// mixin {
// 	add sourceSets.main, 'ChatComponentAPI-forge-refmap.json'
// 	config "chatcomponentapi.mixins.forge.json"
// }

processResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

jar {
	manifest {
		attributes([
			MixinConfigs: 'chatcomponentapi.mixins.forge.json'
		])
	}
}
