plugins {
	id 'java'
}

dependencies {
	implementation project(':base')
}

processResources {
	filesMatching('plugin.yml') {
		expand inputs.properties
	}
}

jar {
	exclude 'org/'
	exclude 'vakiliner/chatcomponentapi/craftbukkit/**'
	exclude 'vakiliner/chatcomponentapi/spigot/**'
	exclude 'vakiliner/chatcomponentapi/paper/**'
}
