plugins {
	id 'java'
}

repositories {
	maven {
		name = 'MinecraftLibs'
		url = 'https://libraries.minecraft.net'
	}

	mavenCentral()
}

dependencies {
	compileOnly "com.google.code.gson:gson:${project.gson_version}"
	compileOnly "com.google.guava:guava:${project.google_guava_version}"
	compileOnly "com.mojang:authlib:${project.authlib_version}"
}

configurations {
	test {
		canBeConsumed = true
		canBeResolved = false
	}
}

artifacts {
	test tasks.named('devJar')
}

processResources {
	inputs.property 'pack_format', project.pack_format

	filesMatching('pack.mcmeta') {
		expand inputs.properties
	}
}

processTestResources {
	inputs.property 'pack_format', project.pack_format

	filesMatching('pack.mcmeta') {
		expand inputs.properties
	}
}
