plugins {
	id 'java'
}

repositories {
	maven {
		name = 'Codemc'
		url = 'https://repo.codemc.io/repository/nms/'
	}

	mavenCentral()
}

dependencies {
	implementation project(':base')
	implementation project(':craftbukkit')
	implementation project(':spigot')
	implementation "com.destroystokyo.paper:paper-api:${project.minecraft_version}-${project.paper_version}"
}
