plugins {
	id 'java'
}

repositories {
	maven {
		name = 'Papermc'
		url = 'https://repo.papermc.io/repository/maven-public/'
	}

	mavenCentral()
}

dependencies {
	implementation project(':core')
	implementation project(':craftbukkit')
	implementation project(':spigot')
	implementation "com.destroystokyo.paper:paper-api:${project.minecraft_version}-${project.paper_version}"
}
